// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAalJ2tc-7Mm7xwr_5Blfp8lvKdlUrKqw4',
    appId: '1:107659324569:web:3519bcaec009407a5a1c08',
    messagingSenderId: '107659324569',
    projectId: 'spot-b-leaf',
    authDomain: 'spot-b-leaf.firebaseapp.com',
    storageBucket: 'spot-b-leaf.firebasestorage.app',
    measurementId: 'G-8RXT9XY80R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAroo0a9zJbgvlrjwSB9cq99FLz_6Dkx_M',
    appId: '1:107659324569:android:4ecde280d5c34d6f5a1c08',
    messagingSenderId: '107659324569',
    projectId: 'spot-b-leaf',
    storageBucket: 'spot-b-leaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBCPvGMpm-dICWSkGm6UtfThLCvqZf1bg',
    appId: '1:107659324569:ios:dc7bc8d7859e76275a1c08',
    messagingSenderId: '107659324569',
    projectId: 'spot-b-leaf',
    storageBucket: 'spot-b-leaf.firebasestorage.app',
    iosBundleId: 'com.example.fyp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBCPvGMpm-dICWSkGm6UtfThLCvqZf1bg',
    appId: '1:107659324569:ios:dc7bc8d7859e76275a1c08',
    messagingSenderId: '107659324569',
    projectId: 'spot-b-leaf',
    storageBucket: 'spot-b-leaf.firebasestorage.app',
    iosBundleId: 'com.example.fyp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAalJ2tc-7Mm7xwr_5Blfp8lvKdlUrKqw4',
    appId: '1:107659324569:web:af0c82122bdd9e605a1c08',
    messagingSenderId: '107659324569',
    projectId: 'spot-b-leaf',
    authDomain: 'spot-b-leaf.firebaseapp.com',
    storageBucket: 'spot-b-leaf.firebasestorage.app',
    measurementId: 'G-KYVW50TF7X',
  );
}
